/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author Administrator
 */
public class gameFrame extends javax.swing.JFrame{
    
    /**
     * Creates new form gameFrame
     */
    static int timeLeft = 15;                //Timer
    static Timer timer;                     //Timer
    static int [] num = new int [4];        //Random number
    static int [] numFinal = new int [4];   //Random number
    static int count = 0;                   //For button
    static int sum = 0;                     //For button 
    static int score = 0;                   //For Label 
    static int bestScore = 0;               //For Label
    
    public gameFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(157, 193, 131));
        numBtn1.setForeground(new java.awt.Color(0, 0, 0));         numBtn1.setBackground(new java.awt.Color(255, 153, 102));
        numBtn2.setForeground(new java.awt.Color(0, 0, 0));         numBtn2.setBackground(new java.awt.Color(255, 153, 102));
        numBtn3.setForeground(new java.awt.Color(0, 0, 0));         numBtn3.setBackground(new java.awt.Color(255, 153, 102));
        numBtn4.setForeground(new java.awt.Color(0, 0, 0));         numBtn4.setBackground(new java.awt.Color(255, 153, 102));
        startBtn.setForeground(new java.awt.Color(0, 0, 0));        startBtn.setBackground(new java.awt.Color(255, 153, 102));
        resetBtn.setForeground(new java.awt.Color(0, 0, 0));    resetBtn.setBackground(new java.awt.Color(255, 153, 102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numBtn2 = new javax.swing.JButton();
        numBtn3 = new javax.swing.JButton();
        numBtn4 = new javax.swing.JButton();
        numBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        secLabel = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bestLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KING OF MATH");
        setSize(new java.awt.Dimension(650, 370));

        numBtn2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        numBtn2.setText("?");
        numBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBtn2ActionPerformed(evt);
            }
        });

        numBtn3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        numBtn3.setText("?");
        numBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBtn3ActionPerformed(evt);
            }
        });

        numBtn4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        numBtn4.setText("?");
        numBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBtn4ActionPerformed(evt);
            }
        });

        numBtn1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        numBtn1.setText("?");
        numBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setText("TIMELEFT :");

        secLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        secLabel.setText("60");

        startBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 20)); // NOI18N
        startBtn.setText("START");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setText("SCORE :");

        scoreLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        scoreLabel.setText("0");

        resetBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 20)); // NOI18N
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel3.setText("BEST :");

        bestLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        bestLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startBtn)
                                .addGap(18, 18, 18)
                                .addComponent(resetBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bestLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(scoreLabel)))))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(secLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bestLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBtn3ActionPerformed
        count++;
        sum+=numFinal[2];
        if(count==2){
            count = 0;
            if(sum==100){
                score++;
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }else{
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }
        }
    }//GEN-LAST:event_numBtn3ActionPerformed

    private void numBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBtn1ActionPerformed
        count++;
        sum+=numFinal[0];
        if(count==2){
            count = 0;
            if(sum==100){
                score++;
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }else{
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }
        }   
    }//GEN-LAST:event_numBtn1ActionPerformed

    private void numBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBtn2ActionPerformed
        count++;
        sum+=numFinal[1];
        if(count==2){
            count = 0;
            if(sum==100){
                score++;
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }else{
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }
        }        
    }//GEN-LAST:event_numBtn2ActionPerformed

    private void numBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBtn4ActionPerformed
        count++;
        sum+=numFinal[3];
        if(count==2){
            count = 0;
            if(sum==100){
                score++;
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }else{
                randomSpecificSum();
                numBtn1.setText(numFinal[0]+"");
                numBtn2.setText(numFinal[1]+"");
                numBtn3.setText(numFinal[2]+"");
                numBtn4.setText(numFinal[3]+"");
                scoreLabel.setText(score+"");
                sum = 0;
            }
        }        
    }//GEN-LAST:event_numBtn4ActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        startBtn.setEnabled(false);
        timer();
        randomSpecificSum();
        numBtn1.setText(numFinal[0]+"");
        numBtn2.setText(numFinal[1]+"");
        numBtn3.setText(numFinal[2]+"");
        numBtn4.setText(numFinal[3]+""); 
        scoreLabel.setText(score+"");
        resetBtn.setEnabled(true);
    }//GEN-LAST:event_startBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        resetBtn.setEnabled(false);
        timer.stop();
        numBtn1.setEnabled(true);
        numBtn2.setEnabled(true);
        numBtn3.setEnabled(true);
        numBtn4.setEnabled(true);
        numBtn1.setText("?");
        numBtn2.setText("?");
        numBtn3.setText("?");
        numBtn4.setText("?");
        timeLeft = 15;
        count = 0;
        sum = 0;
        score = 0;
        secLabel.setText(timeLeft+"");
        scoreLabel.setText(score+"");
        startBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    public static void timer(){
        
            timer = new Timer(1000,new ActionListener(){    
            @Override
            
            public void actionPerformed(ActionEvent e){
                if(--timeLeft==0){
                    secLabel.setText(timeLeft+"");
                    timer.stop(); 
                    bestScore();
                    numBtn1.setEnabled(false);
                    numBtn2.setEnabled(false);
                    numBtn3.setEnabled(false);
                    numBtn4.setEnabled(false);
                }
                secLabel.setText(timeLeft+"");
            }
        });   
        timer.start();
    }
    public static int[] randomSpecificSum(){               
        int logicalSize = 4;    //Keep track of how many element are being used
        int specvalue = 100;
        num[0] = (int)(Math.random() * specvalue + 1);
        num[1] = specvalue-num[0];
        num[2] = (int)(Math.random() * specvalue + 1);
        num[3] = (int)(Math.random() * specvalue + 1);
        
        for(int i=0; i<=3; i++){
            int rnd = (int)(Math.random() * logicalSize);  //Random index
            numFinal[i] = num[rnd];
            
            int removeIndex = rnd;      //Remove already used array
            for(int j = removeIndex; j < logicalSize-1; j++){
                num[j] = num[j+1];  //Move element
            }
            logicalSize--;         //Decrease logicalSize
        }        
        return numFinal;
    }
    public static void bestScore(){
        if(score>bestScore){
            bestScore = score;
            bestLabel.setText(bestScore+"");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel bestLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JButton numBtn1;
    private static javax.swing.JButton numBtn2;
    private static javax.swing.JButton numBtn3;
    private static javax.swing.JButton numBtn4;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel scoreLabel;
    private static javax.swing.JLabel secLabel;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
